### ISSUE TITLE
Request: Add aircon error state

### ISSUE THREAD

**Issue by therokh** [TheNoctambulist/hass-airtouch#13]
### Checklist

- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/thenoctambulist/hass-airtouch/issues?q=is%3Aissue+label%3A%22feature-request%22+).
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).

### Proposal

Hi,

I have an Airtouch5 system that is mostly working fine, but the AC unit is intermittently throwing an error. I'd like to capture that the error has occurred and alert on the error state. I see that pyairtouch seems to support the error state component of the API. Is this able to be added to the HA addon?

**Comment by TheNoctambulist** [comment]
Yes, error information is available from the API. I've added an error code sensor for each air-conditioner that exposes the error information published by the AirTouch in v1.3.0 of the integration. You should be able to use that to set up automations when the error code changes from unknown to an error value.

As you might expect I haven't really been able to test this feature, so let me know if you have any problems!

**Comment by spry-salt** [comment]
For info the error code by default shows as ‘unknown’ on my AirTouch 4. Hopefully that’s a good thing.

**Comment by TheNoctambulist** [comment]
Thanks for testing @spry-salt. Yes, Unknown seems to be the only way to represent the sensor value when there is no error code. I could potentially use zero as the value for no error but it felt cleaner to just leave it unknown. I'm open to alternative suggestions if anyone has other preferences or ideas.

**Comment by spry-salt** [comment]
Maybe could represent no error as ‘false’?

**Comment by therokh** [comment]
Hi thanks for getting to this so quickly. I've installed the add-on and am not so eagerly waiting for my next error to crop  up.

**Comment by TheNoctambulist** [comment]
> Maybe could represent no error as ‘false’?

I did some research and it seems that `"none"` is the canonical value used in Home Assistant for situations like this (which is different to the Python `None` I was using that shows up as "Unknown"). I've released a v1.4.0 update which changes the error code to None when there is no error.

**Comment by spry-salt** [comment]
Wonderful, thank you.

**Comment by therokh** [comment]
Hi, I had an error last night but the add-on state did not change

**Comment by TheNoctambulist** [comment]
@therokh what type of error do you see with the AirTouch? There's a new console update that was just released a couple of days ago to fix a bug where the console crashes and shows a black screen. With that error, the Home Assistant connection also goes down so there's no way to get the error information.

If it's some other error, it might just be that it doesn't trigger any status update from the AirTouch. However, I'm happy to take a look at debug logs to see if there is anything coming across the interface.

**Comment by therokh** [comment]
The error on the Airtouch is reported by the Mitsubishi controller, which is an E16 error. When you tap the error on the console, it pops up a message for 'indoor fan unit anomaly'.
Unfortunately it happens randomly so I can't trigger it to debug the messages.

I do have the console update prompt now so I will update that tonight.

**Comment by TheNoctambulist** [comment]
It shouldn't hurt if you just leave debug logging for the integration turned on until you next see the error. It's a bit chatty but I've had it on for over 24 hours without impacting Home Assistant.
The other option is to turn debug logging on and restart Home Assistant while the error indicator is displayed on the AirTouch console. The restart will trigger the integration to immediately request all status information from the console.

It would also be useful to know if the error indication appear in the official AirTouch 5 app.

**Comment by therokh** [comment]
I've got the debug logging for integration running now

```
2024-12-15 00:09:15.273 DEBUG (MainThread) [pyairtouch.comms.socket] ... CRC : c7 37
2024-12-15 00:09:15.273 DEBUG (MainThread) [pyairtouch.comms.socket] ... Header : At5Header(to_address=253, from_address=128, packet_id=36, message_id=192, message_length=22)
2024-12-15 00:09:15.273 DEBUG (MainThread) [pyairtouch.comms.socket] ... Message : ControlStatusMessage(sub_message=AcStatusMessage(ac_status=[AcStatusData(ac_number=0, power_state=<AcPowerState.ON: 1>, mode=<AcMode.COOL: 4>, fan_speed=<AcFanSpeed.HIGH: 4>, turbo_active=False, bypass_active=False, spill_active=False, timer_set=True, set_point=22.0, temperature=23.1, error_code=0)]))
```


Also seeing some UnsupportedMessage, though that might have happened when I checked the official app?

```
2024-12-15 00:20:41.498 DEBUG (MainThread) [pyairtouch.comms.socket] ... CRC : f7 94
2024-12-15 00:20:41.498 DEBUG (MainThread) [pyairtouch.comms.socket] ... Header : At5Header(to_address=176, from_address=144, packet_id=21, message_id=31, message_length=157)
2024-12-15 00:20:41.498 DEBUG (MainThread) [pyairtouch.comms.socket] ... Message : ExtendedMessage(sub_message=UnsupportedMessage(message_id=0xff83, raw_data=0x010a000232050106180018016725000100026e3c000000036e3c000000046e3c000000056e3c00000006733c00000007783c00000008783c00000009783c0000000a783c0000000b783c0000000c6e3c0000000d6e3a0000000e6e3c0000000f6c3c00000010633c00000011643c00000012643c00000013643c00000014643c00000015643c00000016643c00000017643c000000186b3c000000))
2024-12-15 00:20:45.837 DEBUG (MainThread) [pyairtouch.comms.socket] Read Raw : 55 55 55 ab 00 00 00 b8 00 b8 55 55 55 aa b0 90 17 1f 00 ac ff 83 01 0a 00 01 18 0c 0f 17 7c 0c 2b 16 f9 0a cc 00 ec 00 9f 00 00 00 00 01 0b 05 02 18 05 00 6c 3b 00 ec 00 9f 00 ec 00 00 00 5e 01 3b 02 39 03 2f 04 36 00 02 e8 03 0c 01 03 0c 03 1b 02 03 1b 03 20 03 03 1b 03 20 04 03 1a 03 20 05 03 20 03 20 06 03 1c 03 20 07 03 10 03 1e 08 02 f6 03 10 09 02 f8 02 f8 0a 02 ef 02 f9 0b 02 e9 02 ef 0c 02 d3 02 e9 0d 02 d2 02 d3 0e 02 c4 02 d2 0f 02 c1 02 c4 10 02 c1 02 c9 11 02 b8 02 c9 12 02 b6 02 d5 13 02 cc 02 d5 14 02 be 02 e7 15 02 e7 02 e7 16 02 e7 03 31 17 03 31 03 45 ad 8d
```

**Comment by TheNoctambulist** [comment]
Yeah, unsupported message will come up when you open the official app because that uses a slightly different set of messages that are not documented in the public API. The unsupported messages are just ignored but I include them in the debugging because it can be useful sometimes.

According to that log message, the AirTouch console was not reporting any errors (error_code=0 in the ControlStatusMessage). Did you have an active error state at that time? If not, then perhaps check for the ControlStatusMessage log next time you see the error displayed on the console. If it's not coming through in the API it might be a bug with the AirTouch console that Polyaire can fix.

**Comment by therokh** [comment]
Had our main error appear tonight, and lucky it did because a tech is coming to replace the control board tomorrow. The integration shows no error code, but the API messaging shows an error.
![image](https://github.com/user-attachments/assets/4df8fa8c-c48f-4c89-9d51-88c0dfa567f7)


The integration threw an exception when the error occured:
```
2024-12-17 10:25:42.306 DEBUG (MainThread) [pyairtouch.comms.socket] Read Raw : 55 55 55 ab 00 00 00 22 00 22 55 55 55 aa fd 80 66 c0 00 16 23 00 00 00 00 0e 00 01 00 44 78 c1 3a d4 00 10 d4 00 92 d0 03 00 a5 f0
2024-12-17 10:25:42.306 DEBUG (MainThread) [pyairtouch.comms.socket] ... CRC : a5 f0
2024-12-17 10:25:42.306 DEBUG (MainThread) [pyairtouch.comms.socket] ... Header : At5Header(to_address=253, from_address=128, packet_id=102, message_id=192, message_length=22)
2024-12-17 10:25:42.306 DEBUG (MainThread) [pyairtouch.comms.socket] ... Message : ControlStatusMessage(sub_message=AcStatusMessage(ac_status=[AcStatusData(ac_number=0, power_state=<AcPowerState.OFF: 0>, mode=<AcMode.COOL: 4>, fan_speed=<AcFanSpeed.HIGH: 4>, turbo_active=False, bypass_active=False, spill_active=False, timer_set=True, set_point=22.0, temperature=22.4, error_code=16)]))
2024-12-17 10:25:42.307 ERROR (MainThread) [pyairtouch.comms.socket] Exception from subscriber
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/pyairtouch/comms/socket.py", line 530, in _notify_subscribers
_ = await coro
^^^^^^^^^^
File "/usr/local/lib/python3.12/asyncio/tasks.py", line 631, in _wait_for_one
return f.result() # May raise f.exception().
^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pyairtouch/at5/api.py", line 1087, in _message_received
await self._process_ac_status_message(ac_statuses)
File "/usr/local/lib/python3.12/site-packages/pyairtouch/at5/api.py", line 1138, in _process_ac_status_message
await ac_instance.update_ac_status(ac_status)
File "/usr/local/lib/python3.12/site-packages/pyairtouch/at5/api.py", line 426, in update_ac_status
await self._socket.send(
File "/usr/local/lib/python3.12/site-packages/pyairtouch/comms/socket.py", line 191, in send
message_encoder = self._registry.get_encoder(message.message_id)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/pyairtouch/comms/__init__.py", line 282, in get_encoder
raise NotImplementedError(
NotImplementedError: Encoding of message 0xff10 not implemented
```
And the status messages continue showing the error, but the integration state doesn't change:
```
2024-12-17 10:25:46.440 DEBUG (MainThread) [pyairtouch.comms.socket] Read Raw : 55 55 55 ab 00 00 00 22 00 22 55 55 55 aa fd 80 6b c0 00 16 23 00 00 00 00 0e 00 01 00 44 78 c1 3a d4 00 10 d3 00 92 d0 03 00 ad 26
2024-12-17 10:25:46.440 DEBUG (MainThread) [pyairtouch.comms.socket] ... CRC : ad 26
2024-12-17 10:25:46.440 DEBUG (MainThread) [pyairtouch.comms.socket] ... Header : At5Header(to_address=253, from_address=128, packet_id=107, message_id=192, message_length=22)
2024-12-17 10:25:46.440 DEBUG (MainThread) [pyairtouch.comms.socket] ... Message : ControlStatusMessage(sub_message=AcStatusMessage(ac_status=[AcStatusData(ac_number=0, power_state=<AcPowerState.OFF: 0>, mode=<AcMode.COOL: 4>, fan_speed=<AcFanSpeed.HIGH: 4>, turbo_active=False, bypass_active=False, spill_active=False, timer_set=True, set_point=22.0, temperature=22.4, error_code=16)]))
```

**Comment by TheNoctambulist** [comment]
Thanks, looks like I haven't implemented the error handling properly. That stack trace will be enough for me to track down the problem. I'll push an update when I get a chance (probably over the weekend).

Hopefully the technician is able to solve the underlying issue for you.

**Comment by TheNoctambulist** [comment]
@therokh I've published a v1.5.1 with a fix for the exception. The error sensor should work better now. Thanks for sending through the logs.

**Comment by therokh** [comment]
Thanks! I have updated today. The control board didn't get swapped out, so there's a high chance I'll be able to test this soon :)

**Comment by therokh** [comment]
Hi, the error occurred again today and the sensor updated correctly :)

![image](https://github.com/user-attachments/assets/61621709-e4e8-4b1b-a698-a390637f978c)

**Comment by TheNoctambulist** [comment]
Thanks for the update. Glad to see it is working now.
