### ISSUE TITLE
Struggling to understand how dampers are supposed to work. Is a cover the best representation?

### ISSUE THREAD

**Issue by sddgit** [TheNoctambulist/hass-airtouch#14]
### Checklist

- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/thenoctambulist/hass-airtouch/issues?q=is%3Aissue+label%3A%22feature-request%22+).
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).

### Proposal

I just came here because the previous integration I was using https://github.com/mihailescu2m/hass-airtouch4-platform is about to become defunct, and is no longer maintained.

I have a simple system with 4 zones, each with a damper. No ITC. Everything comes in fine, but I’m struggling with the damper representation as a cover. Using, say, a standard Entity card, you have to tap it, and then switch between the slider and the up/down arrow views in order to change the damper position and switch it on or off. The previous integration represented dampers as fans. This seems to me to be a better fit. A fan has a power button and slider in the one view, and a fan sounds like it fits an air conditioner system better.

I also have a related problem. I use Homekit Bridge to expose the dampers to Homekit. When I tap the icon part of the Homekit card to toggle on and off, only off works. On just gets “opening” and nothing happens in HA. With dampers represented as fans, this hasn’t been a problem.

Very interested in your thoughts.

**Comment by TheNoctambulist** [comment]
A cover entity is the intended way to represent a damper according to the Home Assistant [documentation](https://www.home-assistant.io/integrations/cover/#:~:text=be%20drawn%20open.-,damper,-%3A%20Control%20of%20a). The fan control for an AirTouch system is only associated with the central AC unit. I don't intend to change from cover entities to fan entities.

There aren't many people running the AirTouch system without ITCs, so this hasn't been tested a lot. I think it makes sense for the zone to automatically turn on when you change the damper percentage. You shouldn't have to use both the percentage slider and the open/close buttons. The open button is just a convenience to turn the zone back on to the last used damper percentage. I will release an update to turn the zones on with damper position changes.

Note that you can use a Tile card or Mushroom Cover card to have the controls directly on the dashboard, e.g.:
![image](https://github.com/user-attachments/assets/d35d9805-7ff6-4251-87c8-b9810713c337)
The tile card is the purple card and the mushroom cards are the blue ones.

I don't use HomeKit, so I can't provide much help there. It might depend on what command is being sent for the close and open. If the close is setting the damper position to 0% instead of just sending a "close" command then any subsequent open command would be rejected unless the damper position is set to something >0%. The raw data in the AirTouch messages from debug logging may help work out what is happening there.

I could also look at adding a default opening percentage when an open request is sent for a zone which may solve the HomeKit issue.

**Comment by TheNoctambulist** [comment]
I've published v1.5.0 which will automatically turn the zone on when you change the damper percentage slider.
I looked into setting a default open percentage. As best as I can tell the AirTouch 5 just turns the zone off and sets the damper percentage to 5% when you drag the slider to 0%, so a default percentage is unlikely to ever be used. I can still include a default zone opening percentage feature if the AirTouch 4 behaves differently (debug logging should confirm the behaviour).

**Comment by sddgit** [comment]
Thank you very much for your swift reply and understanding. It's very much appreciated (some coffees on the way...).

I’ve installed V1.5.0, and I think the slider behaviour is now much more intuitive. Terrific.

Now, regarding HomeKit. Its cards are like Tile cards. Tap the icon to do a toggle, tape the rest of the card for more info - the slider in this case. If I tap the icon to close, it gets stuck on "closing..." even though the close actually works. Ditto for opening. However, if you go into the slider view and back out, it has the correct "closed" or "open" status. I have added another cover that I have in HA to HomeKit Bridge, and it suffers the same problem. So this might not be your problem at all. However, here is a debug log with me closing and opening the damper via the icon toggle, in case you can spot anything untoward.
```
2024-12-15 13:04:17.920 DEBUG (MainThread) [pyairtouch.comms.socket] Read Raw     : 55 55 b0 80 00 2f 01 c4 03 ff 39 89 20 26 10 00 11 00 00 00 04 81 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 50 6f 6c 79 61 69 72 65 00 00 00 00 00 00 00 00 32 01 0c 43 00 04 08 00 80 88 1f 1c 20 10 55 4e 49 54 31 00 00 00 00 04 01 00 80 88 00 00 20 10 55 4e 49 54 32 00 00 00 00 04 00 00 80 88 1f 1d 20 10 55 4e 49 54 33 00 00 00 00 04 00 00 80 88 1f 1d 20 10 55 4e 49 54 34 00 00 00 4c 69 76 69 6e 67 00 00 4b 69 74 63 68 65 6e 00 53 74 75 64 79 00 00 00 42 65 64 72 6f 6f 6d 00 47 72 6f 75 70 35 00 00 47 72 6f 75 70 36 00 00 47 72 6f 75 70 37 00 00 47 72 6f 75 70 38 00 00 47 72 6f 75 70 39 00 00 47 72 6f 75 70 41 00 00 47 72 6f 75 70 42 00 00 47 72 6f 75 70 43 00 00 47 72 6f 75 70 44 00 00 47 72 6f 75 70 45 00 00 47 72 6f 75 70 46 00 00 47 72 6f 75 70 47 00 00 ff ff ff ff 80 00 46 41 56 31 00 00 00 00 00 00 46 41 56 32 00 00 00 00 00 00 46 41 56 33 00 00 00 00 00 00 46 41 56 34 00 00 00 00 00 00 80 00 80 00 80 00 80 00 00 00 00 00 00 00 00 00 00 44 1a 00 62 c7 00 00 01 00 19 00 ff e7 ff fe 02 00 56 00 ff e7 ff fe 03 00 57 00 ff e7 ff fe 40 64 19 64 ff e7 41 64 19 64 ff e7 42 28 19 28 ff e7 03 00 19 00 ff e7 44 64 19 00 3e 87 45 64 19 00 3e 87 46 64 19 00 3e 87 47 64 19 00 3e 87 48 64 19 00 3e 87 49 64 19 00 3e 87 4a 64 19 00 3e 87 4b 64 19 00 3e 87 4c 64 19 00 3e 87 4d 64 19 00 3e 87 4e 64 19 00 3e 87 4f 64 19 00 3e 87 13 c0
2024-12-15 13:04:17.921 DEBUG (MainThread) [pyairtouch.comms.socket] ...  CRC     : 13 c0
2024-12-15 13:04:17.921 DEBUG (MainThread) [pyairtouch.comms.socket] ...  Header  : At4Header(to_address=176, from_address=128, packet_id=0, message_id=47, message_length=452)
2024-12-15 13:04:17.922 DEBUG (MainThread) [pyairtouch.comms.socket] ...  Message : UnsupportedMessage(message_id=0x2f, raw_data=0x03ff39892026100011000000048100000000000000000000000000000000000000000000000000000000506f6c7961697265000000000000000032010c430004080080881f1c2010554e49543100000000040100808800002010554e4954320000000004000080881f1d2010554e4954330000000004000080881f1d2010554e4954340000004c6976696e6700004b69746368656e005374756479000000426564726f6f6d0047726f757035000047726f757036000047726f757037000047726f757038000047726f757039000047726f757041000047726f757042000047726f757043000047726f757044000047726f757045000047726f757046000047726f7570470000ffffffff8000464156310000000000004641563200000000000046415633000000000000464156340000000000008000800080008000000000000000000000441a0062c7000001001900ffe7fffe02005600ffe7fffe03005700ffe7fffe40641964ffe741641964ffe742281928ffe703001900ffe7446419003e87456419003e87466419003e87476419003e87486419003e87496419003e874a6419003e874b6419003e874c6419003e874d6419003e874e6419003e874f6419003e87)
2024-12-15 13:04:18.008 DEBUG (MainThread) [pyairtouch.comms.socket] Read Raw     : 55 55 b0 80 03 69 00 06 00 00 00 00 00 00 a3 db
2024-12-15 13:04:18.009 DEBUG (MainThread) [pyairtouch.comms.socket] ...  CRC     : a3 db
2024-12-15 13:04:18.009 DEBUG (MainThread) [pyairtouch.comms.socket] ...  Header  : At4Header(to_address=176, from_address=128, packet_id=3, message_id=105, message_length=6)
2024-12-15 13:04:18.009 DEBUG (MainThread) [pyairtouch.comms.socket] ...  Message : UnsupportedMessage(message_id=0x69, raw_data=0x000000000000)
2024-12-15 13:04:18.081 DEBUG (MainThread) [pyairtouch.comms.socket] Read Raw     : 55 55 b0 80 03 79 00 3c 00 0d 80 88 1f ff 21 f3 ff 00 20 10 04 00 00 01 0d 80 88 00 ff ff ff ff 00 20 10 04 00 00 02 0d 80 88 1f f0 21 f3 ff 00 20 10 04 00 00 03 0d 80 88 1f f0 21 f3 ff 00 20 10 04 00 00 d3 67
2024-12-15 13:04:18.081 DEBUG (MainThread) [pyairtouch.comms.socket] ...  CRC     : d3 67
2024-12-15 13:04:18.081 DEBUG (MainThread) [pyairtouch.comms.socket] ...  Header  : At4Header(to_address=176, from_address=128, packet_id=3, message_id=121, message_length=60)
2024-12-15 13:04:18.081 DEBUG (MainThread) [pyairtouch.comms.socket] ...  Message : UnsupportedMessage(message_id=0x79, raw_data=0x000d80881fff21f3ff002010040000010d808800ffffffff002010040000020d80881ff021f3ff002010040000030d80881ff021f3ff002010040000)
2024-12-15 13:04:18.224 DEBUG (MainThread) [pyairtouch.comms.socket] Read Raw     : 55 55 b0 80 ac 3d 01 04 01 01 00 20 80 00 50 72 6f 67 72 61 6d 31 00 00 00 00 00 00 00 00 00 00 80 00 1a 1a 81 00 80 00 1a 1a 80 00 01 00 50 72 6f 67 72 61 6d 32 00 00 00 00 00 00 00 00 00 00 80 00 1a 1a 80 00 80 00 1a 1a 80 00 02 00 50 72 6f 67 72 61 6d 33 00 00 00 00 00 00 00 00 00 00 80 00 1a 1a 80 00 80 00 1a 1a 80 00 03 00 50 72 6f 67 72 61 6d 34 00 00 00 00 00 00 00 00 00 00 80 00 1a 1a 80 00 80 00 1a 1a 80 00 04 00 50 72 6f 67 72 61 6d 35 00 00 00 00 00 00 00 00 00 00 80 00 1a 1a 80 00 80 00 1a 1a 80 00 05 00 50 72 6f 67 72 61 6d 36 00 00 00 00 00 00 00 00 00 00 80 00 1a 1a 80 00 80 00 1a 1a 80 00 06 00 50 72 6f 67 72 61 6d 37 00 00 00 00 00 00 00 00 00 00 80 00 1a 1a 80 00 80 00 1a 1a 80 00 07 00 50 72 6f 67 72 61 6d 38 00 00 00 00 00 00 00 00 00 00 80 00 1a 1a 80 00 80 00 1a 1a 80 00 fd de
2024-12-15 13:04:18.224 DEBUG (MainThread) [pyairtouch.comms.socket] ...  CRC     : fd de
2024-12-15 13:04:18.224 DEBUG (MainThread) [pyairtouch.comms.socket] ...  Header  : At4Header(to_address=176, from_address=128, packet_id=172, message_id=61, message_length=260)
2024-12-15 13:04:18.224 DEBUG (MainThread) [pyairtouch.comms.socket] ...  Message : UnsupportedMessage(message_id=0x3d, raw_data=0x01010020800050726f6772616d310000000000000000000080001a1a810080001a1a8000010050726f6772616d320000000000000000000080001a1a800080001a1a8000020050726f6772616d330000000000000000000080001a1a800080001a1a8000030050726f6772616d340000000000000000000080001a1a800080001a1a8000040050726f6772616d350000000000000000000080001a1a800080001a1a8000050050726f6772616d360000000000000000000080001a1a800080001a1a8000060050726f6772616d370000000000000000000080001a1a800080001a1a8000070050726f6772616d380000000000000000000080001a1a800080001a1a8000)
2024-12-15 13:04:19.077 DEBUG (MainThread) [pyairtouch.comms.socket] Write Header : At4Header(to_address=128, from_address=176, packet_id=54, message_id=42, message_length=4)
2024-12-15 13:04:19.077 DEBUG (MainThread) [pyairtouch.comms.socket] ...   Message: GroupControlMessage(group_number=2, power=<GroupPowerControl.UNCHANGED: 0>, control_method=<GroupControlMethod.DAMPER: 2>, setting=GroupDamperControl(open_percentage=0))
2024-12-15 13:04:19.078 DEBUG (MainThread) [pyairtouch.comms.socket] ...   CRC    : 81 ba
2024-12-15 13:04:19.078 DEBUG (MainThread) [pyairtouch.comms.socket] ...   Raw    : 55 55 80 b0 36 2a 00 04 02 90 00 00 81 ba
2024-12-15 13:04:19.181 DEBUG (MainThread) [pyairtouch.comms.socket] Read Raw     : 55 55 b0 80 36 2b 00 18 40 64 19 64 ff e7 41 64 19 64 ff e7 02 00 19 28 ff e7 03 00 19 00 ff e7 31 70
2024-12-15 13:04:19.181 DEBUG (MainThread) [pyairtouch.comms.socket] ...  CRC     : 31 70
2024-12-15 13:04:19.181 DEBUG (MainThread) [pyairtouch.comms.socket] ...  Header  : At4Header(to_address=176, from_address=128, packet_id=54, message_id=43, message_length=24)
2024-12-15 13:04:19.182 DEBUG (MainThread) [pyairtouch.comms.socket] ...  Message : GroupStatusMessage(groups=[GroupStatusData(group_number=0, power_state=<GroupPowerState.ON: 1>, control_method=<GroupControlMethod.DAMPER: 0>, spill_active=False, supports_turbo=False, has_sensor=False, battery_status=<SensorBatteryStatus.NORMAL: 0>, temperature=None, damper_percentage=100, set_point=None), GroupStatusData(group_number=1, power_state=<GroupPowerState.ON: 1>, control_method=<GroupControlMethod.DAMPER: 0>, spill_active=False, supports_turbo=False, has_sensor=False, battery_status=<SensorBatteryStatus.NORMAL: 0>, temperature=None, damper_percentage=100, set_point=None), GroupStatusData(group_number=2, power_state=<GroupPowerState.OFF: 0>, control_method=<GroupControlMethod.DAMPER: 0>, spill_active=False, supports_turbo=False, has_sensor=False, battery_status=<SensorBatteryStatus.NORMAL: 0>, temperature=None, damper_percentage=0, set_point=None), GroupStatusData(group_number=3, power_state=<GroupPowerState.OFF: 0>, control_method=<GroupControlMethod.DAMPER: 0>, spill_active=False, supports_turbo=False, has_sensor=False, battery_status=<SensorBatteryStatus.NORMAL: 0>, temperature=None, damper_percentage=0, set_point=None)])
2024-12-15 13:04:19.237 DEBUG (MainThread) [pyairtouch.comms.socket] Read Raw     : 55 55 cf 80 b6 2b 00 18 40 64 19 64 ff e7 41 64 19 64 ff e7 02 00 19 27 ff e7 03 00 19 00 ff e7 70 10
2024-12-15 13:04:19.237 DEBUG (MainThread) [pyairtouch.comms.socket] ...  CRC     : 70 10
2024-12-15 13:04:19.237 DEBUG (MainThread) [pyairtouch.comms.socket] ...  Header  : At4Header(to_address=207, from_address=128, packet_id=182, message_id=43, message_length=24)
2024-12-15 13:04:19.237 DEBUG (MainThread) [pyairtouch.comms.socket] ...  Message : GroupStatusMessage(groups=[GroupStatusData(group_number=0, power_state=<GroupPowerState.ON: 1>, control_method=<GroupControlMethod.DAMPER: 0>, spill_active=False, supports_turbo=False, has_sensor=False, battery_status=<SensorBatteryStatus.NORMAL: 0>, temperature=None, damper_percentage=100, set_point=None), GroupStatusData(group_number=1, power_state=<GroupPowerState.ON: 1>, control_method=<GroupControlMethod.DAMPER: 0>, spill_active=False, supports_turbo=False, has_sensor=False, battery_status=<SensorBatteryStatus.NORMAL: 0>, temperature=None, damper_percentage=100, set_point=None), GroupStatusData(group_number=2, power_state=<GroupPowerState.OFF: 0>, control_method=<GroupControlMethod.DAMPER: 0>, spill_active=False, supports_turbo=False, has_sensor=False, battery_status=<SensorBatteryStatus.NORMAL: 0>, temperature=None, damper_percentage=0, set_point=None), GroupStatusData(group_number=3, power_state=<GroupPowerState.OFF: 0>, control_method=<GroupControlMethod.DAMPER: 0>, spill_active=False, supports_turbo=False, has_sensor=False, battery_status=<SensorBatteryStatus.NORMAL: 0>, temperature=None, damper_percentage=0, set_point=None)])
2024-12-15 13:04:36.418 DEBUG (MainThread) [pyairtouch.comms.socket] Write Header : At4Header(to_address=128, from_address=176, packet_id=55, message_id=42, message_length=4)
2024-12-15 13:04:36.419 DEBUG (MainThread) [pyairtouch.comms.socket] ...   Message: GroupControlMessage(group_number=2, power=<GroupPowerControl.UNCHANGED: 0>, control_method=<GroupControlMethod.DAMPER: 2>, setting=GroupDamperControl(open_percentage=100))
2024-12-15 13:04:36.419 DEBUG (MainThread) [pyairtouch.comms.socket] ...   CRC    : 8d 51
2024-12-15 13:04:36.419 DEBUG (MainThread) [pyairtouch.comms.socket] ...   Raw    : 55 55 80 b0 37 2a 00 04 02 90 64 00 8d 51
2024-12-15 13:04:36.421 DEBUG (MainThread) [pyairtouch.comms.socket] Write Header : At4Header(to_address=128, from_address=176, packet_id=56, message_id=42, message_length=4)
2024-12-15 13:04:36.421 DEBUG (MainThread) [pyairtouch.comms.socket] ...   Message: GroupControlMessage(group_number=2, power=<GroupPowerControl.TURN_ON: 3>, control_method=<GroupControlMethod.UNCHANGED: 0>, setting=None)
2024-12-15 13:04:36.422 DEBUG (MainThread) [pyairtouch.comms.socket] ...   CRC    : 20 cb
2024-12-15 13:04:36.422 DEBUG (MainThread) [pyairtouch.comms.socket] ...   Raw    : 55 55 80 b0 38 2a 00 04 02 03 00 00 20 cb
2024-12-15 13:04:36.746 DEBUG (MainThread) [pyairtouch.comms.socket] Read Raw     : 55 55 b0 80 37 2b 00 18 40 64 19 64 ff e7 41 64 19 64 ff e7 02 64 19 00 ff e7 03 00 19 00 ff e7 81 66
2024-12-15 13:04:36.746 DEBUG (MainThread) [pyairtouch.comms.socket] ...  CRC     : 81 66
2024-12-15 13:04:36.746 DEBUG (MainThread) [pyairtouch.comms.socket] ...  Header  : At4Header(to_address=176, from_address=128, packet_id=55, message_id=43, message_length=24)
2024-12-15 13:04:36.747 DEBUG (MainThread) [pyairtouch.comms.socket] ...  Message : GroupStatusMessage(groups=[GroupStatusData(group_number=0, power_state=<GroupPowerState.ON: 1>, control_method=<GroupControlMethod.DAMPER: 0>, spill_active=False, supports_turbo=False, has_sensor=False, battery_status=<SensorBatteryStatus.NORMAL: 0>, temperature=None, damper_percentage=100, set_point=None), GroupStatusData(group_number=1, power_state=<GroupPowerState.ON: 1>, control_method=<GroupControlMethod.DAMPER: 0>, spill_active=False, supports_turbo=False, has_sensor=False, battery_status=<SensorBatteryStatus.NORMAL: 0>, temperature=None, damper_percentage=100, set_point=None), GroupStatusData(group_number=2, power_state=<GroupPowerState.OFF: 0>, control_method=<GroupControlMethod.DAMPER: 0>, spill_active=False, supports_turbo=False, has_sensor=False, battery_status=<SensorBatteryStatus.NORMAL: 0>, temperature=None, damper_percentage=100, set_point=None), GroupStatusData(group_number=3, power_state=<GroupPowerState.OFF: 0>, control_method=<GroupControlMethod.DAMPER: 0>, spill_active=False, supports_turbo=False, has_sensor=False, battery_status=<SensorBatteryStatus.NORMAL: 0>, temperature=None, damper_percentage=0, set_point=None)])
2024-12-15 13:04:36.819 DEBUG (MainThread) [pyairtouch.comms.socket] Read Raw     : 55 55 b0 80 38 2b 00 18 40 64 19 64 ff e7 41 64 19 64 ff e7 42 64 19 00 ff e7 03 00 19 00 ff e7 be 7c
2024-12-15 13:04:36.819 DEBUG (MainThread) [pyairtouch.comms.socket] ...  CRC     : be 7c
2024-12-15 13:04:36.819 DEBUG (MainThread) [pyairtouch.comms.socket] ...  Header  : At4Header(to_address=176, from_address=128, packet_id=56, message_id=43, message_length=24)
2024-12-15 13:04:36.819 DEBUG (MainThread) [pyairtouch.comms.socket] ...  Message : GroupStatusMessage(groups=[GroupStatusData(group_number=0, power_state=<GroupPowerState.ON: 1>, control_method=<GroupControlMethod.DAMPER: 0>, spill_active=False, supports_turbo=False, has_sensor=False, battery_status=<SensorBatteryStatus.NORMAL: 0>, temperature=None, damper_percentage=100, set_point=None), GroupStatusData(group_number=1, power_state=<GroupPowerState.ON: 1>, control_method=<GroupControlMethod.DAMPER: 0>, spill_active=False, supports_turbo=False, has_sensor=False, battery_status=<SensorBatteryStatus.NORMAL: 0>, temperature=None, damper_percentage=100, set_point=None), GroupStatusData(group_number=2, power_state=<GroupPowerState.ON: 1>, control_method=<GroupControlMethod.DAMPER: 0>, spill_active=False, supports_turbo=False, has_sensor=False, battery_status=<SensorBatteryStatus.NORMAL: 0>, temperature=None, damper_percentage=100, set_point=None), GroupStatusData(group_number=3, power_state=<GroupPowerState.OFF: 0>, control_method=<GroupControlMethod.DAMPER: 0>, spill_active=False, supports_turbo=False, has_sensor=False, battery_status=<SensorBatteryStatus.NORMAL: 0>, temperature=None, damper_percentage=0, set_point=None)])
2024-12-15 13:04:36.829 DEBUG (MainThread) [pyairtouch.comms.socket] Read Raw     : 55 55 cf 80 be 2b 00 18 40 64 19 64 ff e7 41 64 19 64 ff e7 02 64 19 00 ff e7 03 00 19 00 ff e7 f0 53
2024-12-15 13:04:36.829 DEBUG (MainThread) [pyairtouch.comms.socket] ...  CRC     : f0 53
2024-12-15 13:04:36.829 DEBUG (MainThread) [pyairtouch.comms.socket] ...  Header  : At4Header(to_address=207, from_address=128, packet_id=190, message_id=43, message_length=24)
2024-12-15 13:04:36.829 DEBUG (MainThread) [pyairtouch.comms.socket] ...  Message : GroupStatusMessage(groups=[GroupStatusData(group_number=0, power_state=<GroupPowerState.ON: 1>, control_method=<GroupControlMethod.DAMPER: 0>, spill_active=False, supports_turbo=False, has_sensor=False, battery_status=<SensorBatteryStatus.NORMAL: 0>, temperature=None, damper_percentage=100, set_point=None), GroupStatusData(group_number=1, power_state=<GroupPowerState.ON: 1>, control_method=<GroupControlMethod.DAMPER: 0>, spill_active=False, supports_turbo=False, has_sensor=False, battery_status=<SensorBatteryStatus.NORMAL: 0>, temperature=None, damper_percentage=100, set_point=None), GroupStatusData(group_number=2, power_state=<GroupPowerState.OFF: 0>, control_method=<GroupControlMethod.DAMPER: 0>, spill_active=False, supports_turbo=False, has_sensor=False, battery_status=<SensorBatteryStatus.NORMAL: 0>, temperature=None, damper_percentage=100, set_point=None), GroupStatusData(group_number=3, power_state=<GroupPowerState.OFF: 0>, control_method=<GroupControlMethod.DAMPER: 0>, spill_active=False, supports_turbo=False, has_sensor=False, battery_status=<SensorBatteryStatus.NORMAL: 0>, temperature=None, damper_percentage=0, set_point=None)])
2024-12-15 13:04:36.880 DEBUG (MainThread) [pyairtouch.comms.socket] Read Raw     : 55 55 cf 80 c0 2b 00 18 40 64 19 64 ff e7 41 64 19 64 ff e7 42 64 19 00 ff e7 03 00 19 00 ff e7 0f 85
2024-12-15 13:04:36.880 DEBUG (MainThread) [pyairtouch.comms.socket] ...  CRC     : 0f 85
2024-12-15 13:04:36.880 DEBUG (MainThread) [pyairtouch.comms.socket] ...  Header  : At4Header(to_address=207, from_address=128, packet_id=192, message_id=43, message_length=24)
2024-12-15 13:04:36.880 DEBUG (MainThread) [pyairtouch.comms.socket] ...  Message : GroupStatusMessage(groups=[GroupStatusData(group_number=0, power_state=<GroupPowerState.ON: 1>, control_method=<GroupControlMethod.DAMPER: 0>, spill_active=False, supports_turbo=False, has_sensor=False, battery_status=<SensorBatteryStatus.NORMAL: 0>, temperature=None, damper_percentage=100, set_point=None), GroupStatusData(group_number=1, power_state=<GroupPowerState.ON: 1>, control_method=<GroupControlMethod.DAMPER: 0>, spill_active=False, supports_turbo=False, has_sensor=False, battery_status=<SensorBatteryStatus.NORMAL: 0>, temperature=None, damper_percentage=100, set_point=None), GroupStatusData(group_number=2, power_state=<GroupPowerState.ON: 1>, control_method=<GroupControlMethod.DAMPER: 0>, spill_active=False, supports_turbo=False, has_sensor=False, battery_status=<SensorBatteryStatus.NORMAL: 0>, temperature=None, damper_percentage=100, set_point=None), GroupStatusData(group_number=3, power_state=<GroupPowerState.OFF: 0>, control_method=<GroupControlMethod.DAMPER: 0>, spill_active=False, supports_turbo=False, has_sensor=False, battery_status=<SensorBatteryStatus.NORMAL: 0>, temperature=None, damper_percentage=0, set_point=None)])
2024-12-15 13:04:39.545 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall climate.set_fan_mode (c:01JF40Z07SFNKFTWVJS5ZX60WX): entity_id=['climate.studio'], fan_mode=high>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 2822, in _run_service_call_catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1007, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1079, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 757, in async_handle_set_fan_mode_service
    self._valid_mode_or_raise("fan", fan_mode, self.fan_modes)
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 727, in _valid_mode_or_raise
    raise ServiceValidationError(
homeassistant.exceptions.ServiceValidationError: Fan mode high is not valid. Valid fan modes are: Auto, Low, Mid, High, Low/Auto, Mid/Auto, High/Auto
2024-12-15 13:07:15.058 DEBUG (MainThread) [pyairtouch.comms.heartbeat] Sending heartbeat message
2024-12-15 13:07:15.058 DEBUG (MainThread) [pyairtouch.comms.socket] Write Header : At4Header(to_address=144, from_address=176, packet_id=57, message_id=31, message_length=2)
2024-12-15 13:07:15.059 DEBUG (MainThread) [pyairtouch.comms.socket] ...   Message: ExtendedMessage(sub_message=ConsoleVersionRequest())
2024-12-15 13:07:15.060 DEBUG (MainThread) [pyairtouch.comms.socket] ...   CRC    : 23 88
2024-12-15 13:07:15.060 DEBUG (MainThread) [pyairtouch.comms.socket] ...   Raw    : 55 55 90 b0 39 1f 00 02 ff 30 23 88
2024-12-15 13:07:15.189 DEBUG (MainThread) [pyairtouch.comms.socket] Read Raw     : 55 55 b0 90 39 1f 00 09 ff 30 00 05 31 2e 34 2e 34 46 56
2024-12-15 13:07:15.189 DEBUG (MainThread) [pyairtouch.comms.socket] ...  CRC     : 46 56
2024-12-15 13:07:15.189 DEBUG (MainThread) [pyairtouch.comms.socket] ...  Header  : At4Header(to_address=176, from_address=144, packet_id=57, message_id=31, message_length=9)
2024-12-15 13:07:15.189 DEBUG (MainThread) [pyairtouch.comms.socket] ...  Message : ExtendedMessage(sub_message=ConsoleVersionMessage(update_available=False, versions=['1.4.4']))
2024-12-15 13:07:48.281 WARNING (MainThread) [pescea.discovery] No controllers responded to broadcast
NEW LOGS - 
```
Ignore the crash in the log - that's for a different non-Airtouch Daikin unit.

Thanks again.

**Comment by TheNoctambulist** [comment]
Yeah, everything looks ok in the logs. It seems like the close command from HomeKit just came through as setting the position to 0%, and the open command set to 100%. The status update came back from the AirTouch console straight after the commands with the expected values. It might be a problem with the HomeKit bridge integration not processing the status updates when they come through quickly.

I'll close this one for now, but let me know if anything else stands out when using damper control (e.g. if you think the default opening percentage feature will help).

For HomeKit, if you really needed to you could probably wrap the damper control cover entities into a fan entity using the [Template Fan](https://www.home-assistant.io/integrations/fan.template/) integration.

**Comment by sddgit** [comment]
Great, thank you.
