### ISSUE TITLE
Not showing Zones/Dampers

### ISSUE THREAD

**Issue by Arnaud-Albrecht** [TheNoctambulist/hass-airtouch#3]
### System Health details

Logger: homeassistant.components.cover
Source: helpers/entity_platform.py:366
integration: Cover ([documentation](https://www.home-assistant.io/integrations/cover), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+cover%22))
First occurred: 2:00:19 AM (3 occurrences)
Last logged: 11:11:18 AM
Error while setting up airtouch platform for cover

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/airtouch/cover.py", line 44, in async_setup_entry
    zone_device = ac_device.zone_device(airtouch_zone)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/airtouch/devices.py", line 170, in zone_device
    return ZoneDevice(
           ^^^^^^^^^^^
  File "/config/custom_components/airtouch/devices.py", line 127, in __init__
    super().__init__(
  File "/config/custom_components/airtouch/devices.py", line 48, in __init__
    self._register_device()
  File "/config/custom_components/airtouch/devices.py", line 70, in _register_device
    self._device_info["suggested_area"] = self._find_area(suggested_area)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/airtouch/devices.py", line 82, in _find_area
    normalized_name = area_registry.normalize_area_name(name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'homeassistant.helpers.area_registry' has no attribute 'normalize_area_name'. Did you mean: 'normalize_name'?

### Checklist

- [X] I have enabled debug logging for the integration.
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/thenoctambulist/hass-airtouch/issues?q=is%3Aissue+label%3A%22bug%22+)..

### Describe the issue

The Integration does not show the dampers of the zones. in the logs it spills a number of error concerning covers and sensors. I upgraded to the latest version of home assistant and of the polayaire airtouch.

### Reproduction steps

1.
2.
3.
...

### Debug logs

```Text
Logger: homeassistant.components.cover
Source: helpers/entity_platform.py:366
integration: Cover (documentation, issues)
First occurred: 2:00:19 AM (3 occurrences)
Last logged: 11:11:18 AM
Error while setting up airtouch platform for cover

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/airtouch/cover.py", line 44, in async_setup_entry
    zone_device = ac_device.zone_device(airtouch_zone)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/airtouch/devices.py", line 170, in zone_device
    return ZoneDevice(
           ^^^^^^^^^^^
  File "/config/custom_components/airtouch/devices.py", line 127, in __init__
    super().__init__(
  File "/config/custom_components/airtouch/devices.py", line 48, in __init__
    self._register_device()
  File "/config/custom_components/airtouch/devices.py", line 70, in _register_device
    self._device_info["suggested_area"] = self._find_area(suggested_area)
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/airtouch/devices.py", line 82, in _find_area
    normalized_name = area_registry.normalize_area_name(name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'homeassistant.helpers.area_registry' has no attribute 'normalize_area_name'. Did you mean: 'normalize_name'?
```

**Comment by TheNoctambulist** [comment]
This compatibility issue has already been addressed in v0.7.1. Please update to the latest version of the integration.
